# Generated by Django 2.0.6 on 2018-06-14 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='txt',
        ),
        migrations.AddField(
            model_name='test',
            name='ChatRoom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Chat.Msg'),
        ),
    ]
