# Generated by Django 2.0.6 on 2018-06-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0006_auto_20180614_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tst',
            old_name='Room',
            new_name='ChatRoom',
        ),
        migrations.AlterField(
            model_name='tst',
            name='txt',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
