# Generated by Django 2.0.6 on 2018-06-14 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chat', '0008_auto_20180614_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.CharField(blank=True, max_length=10000, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('ChatRoom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Chat.ChatRoom')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='msgs',
            name='ChatRoom',
        ),
        migrations.RemoveField(
            model_name='msg',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='msg',
            name='sender',
        ),
        migrations.AlterField(
            model_name='msg',
            name='txt',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Msgs',
        ),
    ]
